# Simple Neural Nework
Here we try to write a simple neural network to understand how backpropagation algorithm works :)
## Now we create a simple one layer newtork 

### Continue our feedforward network and make it a complete neural network that can predict

In [ ]:
import numpy as np

#activation funcion

#deivative of activation funcion

#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = 
        self.weights1   = 
        self.weights2   =                  
        self.y          = 
        self.output     = 
    #feedfarward function 
    def feedforward(self):
        self.layer1 = 
        self.output = 
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the Error with respect to weights2 and weights1
        d_weights2 = 
        d_weights1 =

        # update the weights with the derivative (slope) of the loss function
        self.weights1 = 
        self.weights2 =

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
    y = np.array([[0],[1],[1],[0]])
   
    nn = # make instance of your NerualNetwork class
   
    #do the iteration for learning
   
    print()



In [1]:
import numpy as np
#activation funcion
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)
#class of your neural network
class NeuralNetwork:
    
    #set features of your neural network
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],2) 
        self.weights2   = np.random.rand(2,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)
    #feedfarward function 
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
    #backpropagate the error
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, ((self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot((self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

#Test what you have done :D 

if __name__ == "__main__":
    X = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
    y = np.array([[0],[1],[1],[0]])
    
    nn = NeuralNetwork(X,y)
    print(nn.weights1)

    for i in range(100):
        nn.feedforward()
        nn.backprop()

    #print(nn.y - nn.output)
    print(nn.weights1)



[[0.22584974 0.35432398]
 [0.71881711 0.46009808]]
[[0.0970963  0.37812284]
 [0.6686741  0.47623547]]


# Python Useful Libraries
Simple Example!

In [1]:
from sklearn.neural_network import MLPClassifier
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = MLPClassifier()
clf.fit(X, y)                         



c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

## OR Function
Let us start with a simple example of Boolean OR

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[0,0],[1,0],[0,1],[1,1]]
y_training=[0,1,1,1]
mynet = MLPClassifier()
mynet.fit(X_training,y_training)



In [3]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)  
mlp.predict([[1,1]])



c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([1])

### Practice: Bipolar OR

Instead of {0, 1}, we can also change the value into bipolar {-1, +1}. Try the following OR gate using Perceptron and MLP.

In [ ]:


X_training=[[1, 1], 
            [1, -1],
            [-1, 1],
            [-1, -1]
           ]
y_training=[1, 
            1,
            1,
            -1
           ]
X_testing=X_training
y_true=y_training


## Multi-Layer Networks

The following code is the example of how you will use Multi-Layer Perceptron (MLP) Neural Network to train, predict. You can also get the weights of the Neural Network.


In [6]:

mlp = MLPClassifier() # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_training)                      # prediction
print(y_pred)                                      # show the output
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
print(mlp.coefs_)                                 # synapsis weights



[1 1 1 0]
[(2, 100), (100, 1)]
[array([[ 1.14517682e-01,  4.41480569e-02, -4.61609935e-06,
        -2.51327879e-01,  2.85634743e-01,  2.87470210e-01,
         1.28830789e-01, -3.30806400e-01,  1.20621380e-01,
         6.43939743e-07, -6.64369264e-02, -2.06172800e-01,
        -2.29836036e-02, -1.79203580e-03,  5.11040231e-02,
         3.95837932e-07,  3.76345871e-07,  1.11386757e-01,
        -2.53238858e-01, -1.38669532e-07,  6.78403614e-02,
        -8.91174013e-03,  1.20620716e-01,  4.07732523e-03,
        -4.68671310e-03, -1.62292251e-07, -2.71990641e-01,
        -2.06199039e-02,  1.47531966e-01,  2.16918239e-05,
         2.30278603e-01, -2.78854818e-01,  3.01411202e-01,
        -7.93403453e-02,  1.00251199e-03, -2.11464045e-01,
        -2.80290051e-01, -2.81071786e-02,  1.13375472e-05,
         2.16483761e-01,  1.68937600e-05,  1.07521356e-01,
         1.71414357e-01, -1.24135015e-02,  1.72178755e-07,
         1.51217002e-02,  1.10532862e-01,  2.52272793e-01,
         1.33153665e-07,

c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Now your Turn!
### Experiments

-  Change the data (X_training, y_training, X_testing)
-  Change the hidden layer of MLP: number of layers (int) or size (n,m)
-  Change activation function of MLP: {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'




In [3]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            1,
            1,
            0
           ]
X_testing = X_training
y_true = y_training
mpl = MLPClassifier(activation = 'identity')
mpl.fit(X_training,y_training)

c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='identity', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [10]:
mlp = MLPClassifier(hidden_layer_sizes=(200,100,300 ), activation='logistic') # set the method
mlp.fit(X_training, y_training)                    # training
y_pred=mlp.predict(X_testing)                      # prediction
print(y_pred)                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('accuracy=',accuracy)                         # show accuracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights



[1 1 1 1]
acuracy= 0.75
[(2, 100), (100, 1)]


c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


2

### XNOR 
Try solve the following Boolean Exclusive Not Or (XNOR) problem. How to improve the accuracy? How many minimum hidden layer is needed to make it 100% accurate?

In [ ]:
X_training=[[1, 1], 
            [1, 0],
            [0, 1],
            [0, 0]
           ]
y_training=[1, 
            0,
            0,
            0
           ]
X_testing=X_training
y_true=y_training
mlp = MLPClassifier(hidden_layer_sizes=(50)) # set the method
mlp.fit(X_training, y_training)                    # training
                                      # show the output
accuracy=metric.accuracy_score(np.array(y_true).flatten(), np.array(y_pred).flatten(), normalize=True)
print('accuracy=',accuracy)                         # show accuracy score


print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
len(mlp.coefs_)                                  # synapsis weights


## Data from File

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
# Returns the mean accuracy on the given test data and labels. 
nn.score(X_test,y_test)

c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9733333333333334

### Your Turn
Creat your network based on only two features of the given dataset.

In [1]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)

c:\users\mahsa\appdata\local\programs\python\python37\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9466666666666667

Try to create and train a neural network for a given dataset with higher accuracy!

In [ ]:
#your answer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
train = pd.read_csv("iris.csv")
features = train.columns[:-1]
X = train[features]
Y =train['Species']
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)
nn = MLPClassifier()
a = nn.fit(X_train,y_train)
nn.score(X_test,y_test)